# Generated by Django 4.2.11 on 2024-03-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='hyperlink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
